desarrollo/config/routes.rb
Rails.application.routes.draw do
  
  resources :tareas
  resources :registros
  
  root 'registro#index'
  get 'registro/edit'
  get 'registro/index'
  get 'registro/new'

    

  get 'tareas/index'
  get 'tareas/new'
  get 'tareas/create'
  get 'tareas/show'
  get 'tareas/edit'
  get 'tareas/update'
  get 'tareas/destroy'
  

  
  
 

  get 'administracion/index'
  get 'home/index'
  get 'reserva/index'
  get 'check_list/index'
  get 'parametros/index'
  get 'registro/index'

end

desarrollo/app/models/tarea.rb
class Tarea < ActiveRecord::Base
  
 # attr_accessible :activo, :descripcion, :prioridad, :titulo
  
  @tarea = Tarea.new({
   :titulo => "Título de prueba",
   :descripcion => "Descripción de prueba",
   :prioridad => 1,
   :activo => true
  });
  @tarea.save();


  @tarea = Tarea.create({
   :titulo => "Título de prueba 2",
   :descripcion => "Descripción de prueba 2",
   :prioridad => 2,
   :activo => true
   });
 
 
  @tarea = Tarea.find(1);
  @tarea.titulo = "Título modificado";
  @tarea.descripcion = "Descripción modificada";
  @tarea.prioridad = 7;
  @tarea.activo = false;
  @tarea.save();

  @tarea = Tarea.find(1);
  @tarea.update_attributes({
   :titulo => "Título modificado",
   :descripcion => "Descripción modificada",
   :prioridad => 7,
   :activo => false
  });

#@tareas = Tarea.update_all(
#   {:activo => false},
#   {:titulo => "Sin título"},
# );
 
#@tarea = Tarea.find(1);
#@tarea.destroy();

#@tareas = Tarea.destroy_all(
#   {:activo => false}
# );
 
# @tareas = Tarea.select("titulo, descripcion").where(:activo => true).order("titulo").limit(3);
# attr_accessible :activo, :descripcion, :prioridad, :titulo
 
    
    
end

desarrollo/app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  
  def index
    @tareas = Tarea.select("id, titulo, descripcion").where(:activo => true).order("id DESC");
  end

  def new
    @tarea = Tarea.new();
  end


  def show
     @tarea = Tarea.find(params[:id]);
  end


  def edit
      @tarea = Tarea.find(params[:id]);
      @titulo = @tarea.titulo;
      @descripcion = @tarea.descripcion;
      @prioridad = @tarea.prioridad;
  end


  def update
      @titulo = params[:tarea]["titulo"];
      @descripcion = params[:tarea]["descripcion"];
      @prioridad = params[:tarea]["prioridad"];
      @tarea = Tarea.find(params[:id]);
      @tarea.titulo = @titulo;
      @tarea.descripcion = @descripcion;
      @tarea.prioridad = @prioridad;
      if @tarea.save()
         redirect_to tareas_path, :notice => "La tarea ha sido modificada";
      else
         render "edit";
      end
  end

   def destroy
      @tarea = Tarea.find(params[:id]);
      if @tarea.destroy()
         redirect_to tareas_path, :notice => "La tarea ha sido eliminada";
      else
         redirect_to tareas_path, :notice => "La tarea NO ha podido ser eliminada";
      end
   end

  
  def create
      #Recuperamos las varibles POST que vinieron desde la acción new.
      @titulo = params[:tarea][:titulo];
      @descripcion = params[:tarea][:descripcion];
      @prioridad = params[:tarea][:prioridad];
      #Creamos el objeto con los valores a ingresar.
      @tarea = Tarea.new({
         :titulo => @titulo,
         :descripcion => @descripcion,
         :prioridad => @prioridad,
         :activo => true
      });
      #Verificamos si la tarea ha podido ser guardado correctamente.
      if @tarea.save()
         redirect_to tareas_path, :notice => "La tarea ha sido insertada";
      else
         render "new";
      end
   end
 
 
   # def finalizar
   #   @tarea = Tarea.find(params[:id]);
   #   @tarea.activo = false;
   #   if @tarea.save()
   #      redirect_to tareas_path, :notice => "La tarea ha sido finalizada";
   #   else
   #      redirect_to tareas_path, :notice => "La tarea NO ha podido finalizar";
   #   end
   #end


  
end

desarrollo/app/helpers/tareas_helper.rb
module TareasHelper
end

desarrollo/app/views/tareas/_formulario_guardar_tareas.html.erb
<%= form_for @tarea do |f| %> 
   <p> 
      <%= f.label :titulo, "Título" %>
      
      <%= f.text_field :titulo, {:value => @titulo} %>
   </p>
   <p> 
      <%= f.label :descripcion, "Descripción" %>
      
      <%= f.text_area :descripcion, {:value => @descripcion} %>
   </p>
   <p>
      <%= f.label :prioridad, "Prioridad" %>
      
      <%= f.text_field :prioridad, {:value => @prioridad, :size => "1", :maxlength => 1} %>
   </p>
   <p>
      <%= f.submit "Enviar" %> <%= link_to "Cancelar", tareas_path %>
   </p>
<% end %>

desarrollo/app/views/tareas/create.html.erb
<h1>Tareas#create</h1>
<p>Find me in app/views/tareas/create.html.erb</p>

desarrollo/app/views/tareas/destroy.html.erb
<h1>Tareas#destroy</h1>
<p>Find me in app/views/tareas/destroy.html.erb</p>

desarrollo/app/views/tareas/edit.html.erb
<h2> Modificar tarea </h2>
<%= render :partial => "formulario_guardar_tareas.html" %>

desarrollo/app/views/tareas/index.html.erb
<h2> Lista de tareas </h2>
    <p> <%= link_to "Crear nueva tarea", new_tarea_path %> </p>
<ul>
<% @tareas.each do |t| %>
        <li>
        <h3> <%= t.titulo %> </h3>
            <p>
            <%= link_to "Ver", t %>
            <%= link_to "Editar", edit_tarea_path(t) %>
            <%= link_to "Eliminar", t, :confirm => "Seguro desea eliminar esta tarea?", :method => :delete %> 
            </p>
        </li>
<% end %>

</ul>

desarrollo/app/views/tareas/index2.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<title>Web adaptable con Media Queries</title>
 
<!--css -->
<link href="style.css" rel="stylesheet" type="text/css">
<link href="media-queries.css" rel="stylesheet" type="text/css">
 
<!-- html5.js - IE  9 -->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
 
<!-- css3-mediaqueries.js - IE  9 -->
<!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
 
</head>
 
<body>
 
<div id="pagewrap">
 
    <header id="header">
 
        <hgroup>
            <img src="logo.png" id="logo" alt="logo"  >
            <h1 id="site-description">Responsive Design con CSS3 Media Queries</h1>
        </hgroup>
 
        <nav>
            <ul id="main-nav" class="clearfix">
                <li><a href="#">Home</a></li>
                <li><a href="#">Quienes somos</a></li>
                <li><a href="#">Servicios</a></li>
                <li><a href="#">Portafolio</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contacto</a></li>
 
            </ul>
            <!-- nav --> 
        </nav>
 
        <form id="searchform">
            <input id="s" placeholder="Search" type="search">
        </form>
 
    </header>
    <!-- /#header -->
 
    <div id="content">
 
        <article class="post clearfix">
 
                <h2 class="post-title"><a href="#">HTML5 </a></h2>
 
            <figure class="post-imagen"> 
                <img src="html5-imagen.jpg"> 
            </figure>
            <p><strong>HTML5</strong> (<em><strong>H</strong>yper<strong>T</strong>ext <strong>M</strong>arkup <strong>L</strong>anguage</em>, versión 5) es la quinta revisión importante del lenguaje básico de la <a href="http://es.wikipedia.org/wiki/World_Wide_Web" title="World Wide Web">World Wide Web</a>, <a href="http://es.wikipedia.org/wiki/HTML" title="HTML">HTML</a>. HTML5 especifica dos variantes de sintaxis para HTML: un «clásico» HTML (text/html), la variante conocida como <em>HTML5</em> y una variante <a href="http://es.wikipedia.org/wiki/XHTML" title="XHTML">XHTML</a> conocida como sintaxis <em>XHTML5</em> que deberá ser servida como XML (XHTML) (application/xhtml+xml).<a href="http://es.wikipedia.org/wiki/HTML5#cite_note-w3cSpec-0">1</a> <a href="http://es.wikipedia.org/wiki/HTML5#cite_note-franganilloHTML5-1">2</a> Esta es la primera vez que HTML y XHTML se han desarrollado en paralelo.</p>
            <p>Todavía se encuentra en modo experimental, lo cual indica la misma   W3C; aunque ya es usado por múltiples desarrolladores web por sus   avances, mejoras y ventajas.</p>
            <p>Al no ser reconocido en viejas versiones de navegadores por sus   nuevas etiquetas, se le recomienda al usuario común actualizar a la   versión más nueva, para poder disfrutar de todo el potencial que provee   HTML5.</p>
        </article>
        <article class="post clearfix">
 
          <h2 class="post-title"><a href="#">CSS3</a></h2>
 
            <figure class="post-imagen"> 
                <img src="css3-imagen.jpg"> 
            </figure>
            <p>El nombre <strong>hojas de estilo en cascada</strong> viene del <a href="http://es.wikipedia.org/wiki/Idioma_ingl%C3%A9s" title="Idioma inglés">inglés</a> <em>Cascading Style Sheets</em>, del que toma sus siglas. CSS es un lenguaje usado para definir la presentación de un documento estructurado escrito en <a href="http://es.wikipedia.org/wiki/HTML" title="HTML">HTML</a> o <a href="http://es.wikipedia.org/wiki/XML" title="XML">XML</a><a href="http://es.wikipedia.org/wiki/CSS3#cite_note-1">2</a> (y por extensión en <a href="http://es.wikipedia.org/wiki/XHTML" title="XHTML">XHTML</a>). </p>
            <p>El <a href="http://es.wikipedia.org/wiki/W3C" title="W3C">W3C</a> (World Wide Web Consortium) es el encargado de formular la especificación de las <a href="http://es.wikipedia.org/wiki/Hojas_de_estilo" title="Hojas de estilo">hojas de estilo</a> que servirán de estándar para los <a href="http://es.wikipedia.org/wiki/Agentes_de_usuario" title="Agentes de usuario">agentes de usuario</a> o <a href="http://es.wikipedia.org/wiki/Navegadores" title="Navegadores">navegadores</a>.<br>
            La idea que se encuentra detrás del desarrollo de CSS es separar la <em>estructura</em> de un documento de su <em>presentación</em>.
      </article>
        <!-- /.post -->
 
  </div>
    <!-- /#content --> 
 
    <aside id="sidebar">
 
        <section class="widget">
            <h4 class="widgettitulo">Noticias</h4>
            <ul>
                <li><a href="#">Diseño web</a></li>
                <li><a href="#">Diseño Grafico</a></li>
                <li><a href="#">Wordpress </a></li>
                <li><a href="#">Joomla </a></li>
                <li><a href="#">Drupal </a></li>
                <li><a href="#">Redes Sociales </a></li>
                <li><a href="#">SEO </a></li>
            </ul>
        </section>
        <section class="widget">
            <h4 class="widgettitulo">Sitos Web</h4>
            <ul>
                <li><a href="http://www.tutosytips.com/">Tutosytips.com</a></li>
                <li><a href="http://www.wordpress.org.com/">Wordpress</a></li>
                <li><a href="http://www.Joomla.org/">Joomla</a></li>
                <li><a href="http://www.twetter.com/">Twetter </a></li>
                <li><a href="http://www.facebook.com/">Facebook </a></li>
                <li><a href="http://www.youtube.com/">YouTube </a></li>
                <li><a href="#">SEO </a></li>
            </ul>
        </section>
 
    </aside>
    <!-- /#sidebar -->
 
    <footer id="footer">
 
        <p>Tutorial por <a href="http://tutosytips.com/">tutosytips</a></p>
 
    </footer>
    <!-- footer -->     
</div>
<!-- /#pagewrap -->
</body>
</html>

desarrollo/app/views/tareas/new.html.erb
<h2> Nueva tarea </h2>
<%= render :partial => "formulario_guardar_tareas.html" %>

desarrollo/app/views/tareas/show.html.erb
<h2> <%= @tarea.titulo %> </h2>
    <div>
       <%= simple_format @tarea.descripcion %>
    </div>
    <p> <%= link_to "Volver", tareas_path %> </p>

desarrollo/app/views/tareas/update.html.erb
<h1>Tareas#update</h1>
<p>Find me in app/views/tareas/update.html.erb</p>