desarrollo/config/routes.rb
Rails.application.routes.draw do
  
  resources :tareas
  resources :registros
  
  root 'registro#index'
  get 'registro/edit'
  get 'registro/index'
  get 'registro/new'

    

  get 'tareas/index'
  get 'tareas/new'
  get 'tareas/create'
  get 'tareas/show'
  get 'tareas/edit'
  get 'tareas/update'
  get 'tareas/destroy'
  

  
  
 

  get 'administracion/index'
  get 'home/index'
  get 'reserva/index'
  get 'check_list/index'
  get 'parametros/index'
  get 'registro/index'

end

desarrollo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--css 
    <link href="style.css" rel="stylesheet" type="text/css">
    <link href="media-queries.css" rel="stylesheet" type="text/css"> 
     -->

    <title><%= content_for?(:title) ? yield(:title) : "TAXI XPRESS" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  
  
  
<body>
  
<h1> Organizador </h1>
<!-- Muestra los mensajes redirigidos por otra página si los hay -->
<% flash.each do |key, value| %>
   <p> <%= value %> </p>
<% end %>
<% flash.each do |key, value| %>
   <p> <%= value %> </p>
<% end %>





      <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%=root_path%>">Taxi Xpress</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Reserva", reserva_index_path  %></li>
            <li><%= link_to "Administración", administracion_index_path  %></li>
            <li><%= link_to "Parámetros", parametros_index_path  %></li>
            <li><%= link_to "CheckList", check_list_index_path %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Conductor", "/path2"  %></li>
            <li><%= link_to "Vehículo", "/path2"  %></li>
          </ul>
          </li>
            <li><%= link_to "Registro", registro_index_path  %>
          </ul>
        </div>
      </div>
    </div>



    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->



      <footer>
        <p>&copy; Consultora Informática JJJC</p>
      </footer>


    </div> <!-- /container -->






  </body>
</html>