desarrollo/config/routes.rb
Rails.application.routes.draw do
  
  resources :tareas
  resources :registros
  
  root 'registro#index'
  get 'registro/edit'
  get 'registro/index'
  get 'registro/new'

    

  get 'tareas/index'
  get 'tareas/new'
  get 'tareas/create'
  get 'tareas/show'
  get 'tareas/edit'
  get 'tareas/update'
  get 'tareas/destroy'
  

  
  
 

  get 'administracion/index'
  get 'home/index'
  get 'reserva/index'
  get 'check_list/index'
  get 'parametros/index'
  get 'registro/index'

end

desarrollo/app/models/registro.rb
class Registro < ActiveRecord::Base
    
@registro = Registro.new({
   :name => "Carlos Caycho Tarrillo",
   :phone => "954122918",
   :homeaddress  => "Izaguirre,Los Olivos",
   :endaddress => "Lima,Lima",
   :mail => "carlos.caycho.tarrillo@hotmail.com",
   :transfer_date => "12/04/2015",
   :hour_transfer => "12:34am",
   :observation => "Observacion"
  });
  @registro.save();
    
    
@registro = Registro.new({
   :name => "Jorge Salazar Cuipal",
   :phone => "954122918",
   :homeaddress  => "Izaguirre,Los Olivos",
   :endaddress => "Lima,Lima",
   :mail => "carlos.caycho.tarrillo@hotmail.com",
   :transfer_date => "12/04/2015",
   :hour_transfer => "12:34am",
   :observation => "Observacion"
  });
  @registro.save();
  
end

desarrollo/app/controllers/registro_controller.rb
class RegistroController < ApplicationController
    def index
        @registros = Registro.select("name, phone, mail,transfer_date,hour_transfer").order("name DESC");
    end

      def new
        @registro = Registro.new();
      end
    
      def show
         @registro = Registro.find(params[:id]);
      end


      def edit
          @registro = Registro.find(params[:id]);
          @name = @registro.name;
          @homeaddress = @registro.homeaddress;
          @endaddress = @registro.endaddress;
          @phone = @registro.phone;
          @mail = @registro.mail;
          @transfer_date = @registro.transfer_date;
          @hour_transfer = @registro.hour_transfer;
          @observation = @registro.observation;
      end


      def update
            @name = params[:registro]["name"];
            @homeaddress = params[:registro]["homeaddress"];
            @endaddress = params[:registro]["endaddress"];
            @phone = params[:registro]["phone"];
            @mail = params[:registro]["mail"];
            @transfer_date = params[:registro]["transfer_date"];
            @hour_transfer = params[:registro]["hour_transfer"];
            @observation = params[:registro]["observation"];        
            @registro = Registro.find(params[:id]);
             @registro.name=@name;
              @registro.homeaddress=@homeaddress;
               @registro.endaddress=@endaddress;
                @registro.phone=@phone;
                 @registro.mail=@mail;
                  @registro.transfer_date=@transfer_date;
                   @registro.hour_transfer=@hour_transfer;
                    @registro.observation=@observation;
            if @registro.save()
                redirect_to registro_index, :notice => "La tarea ha sido modificada";
            else
            render "edit";
            end
        end
  
  
     def destroy
          @registro = Registro.find(params[:id]);
          if @tarea.destroy()
             redirect_to registro_index, :notice => "La tarea ha sido eliminada";
          else
             redirect_to registro_index, :notice => "La tarea NO ha podido ser eliminada";
          end
     end
   

    def create
          #Recuperamos las varibles POST que vinieron desde la acción new.
          @name = params[:registro][:name];
          @homeaddress = params[:registro][:homeaddress];
          @endaddress = params[:registro][:endaddress];
          @phone = params[:registro][:phone];
          @mail = params[:registro][:mail];
          @transfer_date = params[:registro][:transfer_date];
          @hour_transfer = params[:registro][:hour_transfer];
          @observation = params[:registro][:observation];
          #Creamos el objeto con los valores a ingresar.
          @registro = Registro.new({
             :name => @name,
             :homeaddress => @homeaddress,
             :endaddress => @endaddress,
             :phone => @phone,
             :mail => @mail,
             :transfer_date => @transfer_date,
             :hour_transfer => @hour_transfer,
             :observation =>   @observation
          });
          
          #Verificamos si la tarea ha podido ser guardado correctamente.
          if @registro.save()
             redirect_to registro_index, :notice => "El registro ha sido insertada";
          else
             render "new";
          end
      end
   
end

desarrollo/app/helpers/registro_helper.rb
module RegistroHelper
end

desarrollo/app/views/registro/_registro_cod.html.erb
<h4>POR FAVOR, LLENA TUS DATOS Y HAS TU RESERVA</h4>
<h2>Pronto recibirás un correo de confirmación. La confirmación de la misma llegará a su correo.</h2>
</br>
</br>
<%= form_for @registro do |f| %> 
<label></label>
<%= f.label :descripcion, "NOMBRE Y APELLIDOS:" %>
<%= f.text_field :name, {:value => @name} %>

<%= f.label :descripcion, "RECÓGEME (calle, distrito)" %>
<%= f.text_field :homeaddress, {:value => @homeaddress}%>

<%= f.label :descripcion, "LLÉVAME (calle, distrito)" %>
<%= f.text_field :endaddress,  {:value => @endaddress}%>

<%= f.label :descripcion, "TELÉFONO:" %>
<%= f.text_field :phone,  {:value => @phone}%>

<%= f.label :descripcion, "EMAIL:" %>
<%= f.text_field :mail, {:value => @mail}%>

<%= f.label :descripcion, "DÍA:" %>
<%= f.date_field :transfer_date, {:value => @transfer_date}%>

<%= f.label :descripcion, "HORA:" %>
<%= f.time_field :hour_transfer, {:value => @hour_transfer}%>

<%= f.label :descripcion, "OBSERVACIÓN:" %>
<%= f.text_area :observation, {:value => @observation} %>
<%= f.submit "Enviar" %> <%= link_to "Cancelar", registro_index_path %>
<% end %>

desarrollo/app/views/registro/edit.html.erb
<h2> Modificar Registro </h2>
<%= render :partial => "registro_cod.html" %>

desarrollo/app/views/registro/index.html.erb
<h4> LISTA DE RESERVAS PENDIENTES DE CONFIRMACIÓN </h4>
    <p> <%= link_to "Crear nuevo registro", registro_new_path %> </p>
<ul>
<% @registros.each do |t| %>
        <li>
        <h2> <%= t.transfer_date %> - <%= t.mail %> - <%= t.name %>  -  <%= t.phone %>  <%= link_to "Ver", t.id  %></h2>
            
            
            
            </br>
        </li>
<% end %>
</ul>

desarrollo/app/views/registro/new.html.erb
<h2> Nuevo Registro </h2>
<%= render :partial => "registro_cod.html" %>